name = "cityrailgame"
pages_build_output_dir = "."
compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CITYRAIL_KV"
id = "fc84a1ee218b458587b535112c61e269"
